### ISSUE TITLE
License concerns

### ISSUE THREAD

**Issue by mrneo240** [sternmull/yalloc#1]
Hello!
I have recently used this library in a project of mine.
The license you includes is MIT but does not contain your copyright nor the year.
I have thus included your license as is, but I would prefer to have a completed one if possible. I don't mind including a note about where to obtain your original release, but It would be better with a proper license file.

Goals:
Have an amended license showing your copyright and the year.

Thank you for your time.

**Comment by sternmull** [comment]
Thank you for pointing that out! Updated with commit 2d38f57d64f38eedc2c314e1c1090fb9cf26379f
